/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    knowledge: Knowledge;
    'knowledge-chunks': KnowledgeChunk;
    'chat-sessions': ChatSession;
    'chat-messages': ChatMessage;
    roles: Role;
    providers: Provider;
    agents: Agent;
    'agent-runs': AgentRun;
    'agent-memories': AgentMemory;
    guardrails: Guardrail;
    'eval-cases': EvalCase;
    'eval-runs': EvalRun;
    'eval-results': EvalResult;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    knowledge: KnowledgeSelect<false> | KnowledgeSelect<true>;
    'knowledge-chunks': KnowledgeChunksSelect<false> | KnowledgeChunksSelect<true>;
    'chat-sessions': ChatSessionsSelect<false> | ChatSessionsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'agent-runs': AgentRunsSelect<false> | AgentRunsSelect<true>;
    'agent-memories': AgentMemoriesSelect<false> | AgentMemoriesSelect<true>;
    guardrails: GuardrailsSelect<false> | GuardrailsSelect<true>;
    'eval-cases': EvalCasesSelect<false> | EvalCasesSelect<true>;
    'eval-runs': EvalRunsSelect<false> | EvalRunsSelect<true>;
    'eval-results': EvalResultsSelect<false> | EvalResultsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      runAgent: TaskRunAgent;
      reindexKnowledge: TaskReindexKnowledge;
      indexMemory: TaskIndexMemory;
      summarizeMemory: TaskSummarizeMemory;
      runEval: TaskRunEval;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * User = human; Admin = administrator; Agent = agent security principal.
   */
  type: 'User' | 'Admin' | 'Agent';
  role?: (number | null) | Role;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  description?: string | null;
  /**
   * What this role grants. Used by collection access rules via `requirePermission`. Admins always have full access.
   */
  permissions?: ('content.write' | 'runs.read')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL path, e.g. my-first-post
   */
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  author?: (number | null) | User;
  published?: boolean | null;
  publishedDate?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge".
 */
export interface Knowledge {
  id: number;
  title: string;
  /**
   * Source text (alternative to uploading a file). Chunked and embedded for retrieval. Store only internal/knowledge documents here — do NOT put personal or customer data in this collection.
   */
  content?: string | null;
  /**
   * Optional source file (txt, md, csv, json, html, pdf). Text is extracted, chunked and embedded on publish.
   */
  file?: (number | null) | Media;
  /**
   * Optional link to the original source (e.g. the blog post URL).
   */
  sourceUrl?: string | null;
  /**
   * Who may retrieve this document. Retrieval and normal reads both enforce this.
   */
  visibility: 'public' | 'authenticated' | 'role' | 'private';
  /**
   * Owner (used by `private` visibility). Set automatically on create.
   */
  owner?: (number | null) | User;
  /**
   * Roles allowed to retrieve this document when visibility is `role`.
   */
  allowedRoles?: (number | Role)[] | null;
  /**
   * Plain text actually used for indexing (extracted from the file, or the content field).
   */
  extractedText?: string | null;
  /**
   * Indexing state, maintained by the reindex queue job.
   */
  indexStatus?: ('idle' | 'pending' | 'processing' | 'indexed' | 'failed') | null;
  chunkCount?: number | null;
  indexError?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-chunks".
 */
export interface KnowledgeChunk {
  id: number;
  knowledge: number | Knowledge;
  chunkIndex: number;
  content: string;
  embeddingModel: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions".
 */
export interface ChatSession {
  id: number;
  sessionId: string;
  /**
   * Agent this conversation belongs to (agent-scoped chat history).
   */
  agent?: (number | null) | Agent;
  /**
   * Number of messages already folded into long-term memory by the summarisation job.
   */
  summarizedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  /**
   * Agent display name.
   */
  name: string;
  /**
   * Single-shot runs one operation and returns a result; streaming is conversational (chatbot).
   */
  kind: 'single-shot' | 'streaming';
  /**
   * Active agents may be triggered; inactive agents are disabled.
   */
  status: 'active' | 'inactive';
  /**
   * What the agent can do. "knowledge" retrieves context from the framework Knowledge base; "memory" retrieves the agent's long-term memory before answering.
   */
  capabilities?: ('knowledge' | 'memory')[] | null;
  /**
   * CMS skills the agent may call during a run. Calls run as the agent principal, so access rules apply.
   */
  tools?: ('searchKnowledge' | 'listContent' | 'getContent' | 'countContent' | 'saveMemory')[] | null;
  /**
   * Who may call POST /api/agents/:id/run. Use "public" for customer-facing FAQ agents; "admin" for agents that touch sensitive data.
   */
  runAccess: 'public' | 'authenticated' | 'admin';
  /**
   * Guardrails: scan input for prompt-injection and redact secrets/PII from output. "enforce" also blocks flagged input. See docs/agents.md.
   */
  safetyMode?: ('off' | 'monitor' | 'enforce') | null;
  /**
   * Opt-in: also run a semantic (model-based) prompt-injection check on input. Costs an extra model call per run; off by default.
   */
  semanticSafety?: boolean | null;
  /**
   * Opt-in: when true, a failing evaluation gate (EvalRun.gatePassed = false) deactivates this agent.
   */
  gateEnforced?: boolean | null;
  /**
   * The User principal (type Agent) this agent acts as for access control / MCP keys. The MCP access key is issued against this principal in the admin MCP → API Keys collection — never store the key itself on this record.
   */
  user: number | User;
  /**
   * Model provider used by this agent.
   */
  provider?: (number | null) | Provider;
  /**
   * Model id to use from the chosen Provider.
   */
  model?: string | null;
  /**
   * System prompt / instructions for this agent.
   */
  prompt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  /**
   * Display name, e.g. openai-prod, deepseek.
   */
  name: string;
  /**
   * Which SDK adapter to use for this provider.
   */
  provider: 'openai' | 'deepseek' | 'anthropic' | 'local';
  /**
   * Models this provider exposes.
   */
  models?:
    | {
        /**
         * e.g. text-embedding-3-small, gpt-4o, deepseek-chat.
         */
        modelId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Environment/secret variable name holding the API key, e.g. OPENAI_API_KEY. Takes precedence over the pasted key below. Never store the key itself here.
   */
  keyRef?: string | null;
  /**
   * Optional: paste the provider API key here (stored encrypted; never returned to the browser). Use keyRef for env/secret-manager instead. Only Admins can edit this.
   */
  apiKey?: string | null;
  /**
   * Optional base URL override (local/self-hosted providers).
   */
  baseUrl?: string | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: number;
  session: number | ChatSession;
  role: 'user' | 'assistant' | 'system';
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs".
 */
export interface AgentRun {
  id: number;
  agent: number | Agent;
  status: 'queued' | 'running' | 'succeeded' | 'failed';
  triggeredBy: 'api' | 'queue' | 'schedule';
  input?: string | null;
  output?: string | null;
  error?: string | null;
  /**
   * Guardrails flagged this run (prompt-injection and/or redactions).
   */
  flagged?: boolean | null;
  /**
   * Comma-separated guardrail reasons (e.g. prompt-injection:dan, email).
   */
  flagReasons?: string | null;
  session?: (number | null) | ChatSession;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-memories".
 */
export interface AgentMemory {
  id: number;
  /**
   * The agent this memory belongs to.
   */
  agent: number | Agent;
  /**
   * The agent principal who may read this memory (set automatically).
   */
  owner: number | User;
  /**
   * Taxonomy: a single fact, a user/agent preference, or a session summary.
   */
  kind?: ('fact' | 'preference' | 'summary') | null;
  /**
   * Short, non-sensitive memory text. Never store PII or credentials here.
   */
  content: string;
  /**
   * Optional source session (for memories produced by summarisation).
   */
  session?: (number | null) | ChatSession;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guardrails".
 */
export interface Guardrail {
  id: number;
  name: string;
  enabled?: boolean | null;
  /**
   * Whether the rule applies to user input, model output, or both.
   */
  direction?: ('input' | 'output' | 'both') | null;
  /**
   * What to do when the pattern matches.
   */
  action?: ('flag' | 'block' | 'redact') | null;
  /**
   * Regular expression source (no slashes), e.g. \b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b for a card number.
   */
  pattern: string;
  /**
   * Regex flags, e.g. "i" (case-insensitive) or "gi" (global).
   */
  flags?: string | null;
  /**
   * Replacement text when action is "redact".
   */
  replacement?: string | null;
  /**
   * Optional: scope this rule to one agent. Leave empty to apply to all agents.
   */
  agent?: (number | null) | Agent;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eval-cases".
 */
export interface EvalCase {
  id: number;
  name: string;
  description?: string | null;
  /**
   * The agent this case evaluates.
   */
  agent: number | Agent;
  enabled?: boolean | null;
  /**
   * Correctness compares the output to `expected`; tool-use asserts `expected` (a skill name) was called; safety asserts the run is flagged (or not) per `expectFlagged`.
   */
  type: 'correctness' | 'tool-use' | 'safety';
  /**
   * How `expected` is matched for correctness cases. "judge" uses the agent’s model to grade meaning (costs an extra model call).
   */
  match?: ('contains' | 'exact' | 'judge') | null;
  /**
   * The prompt sent to the agent.
   */
  input: string;
  /**
   * Reference: the expected answer text (correctness) or the expected skill name (tool-use).
   */
  expected?: string | null;
  /**
   * Safety: when true, the case passes only if the run is guardrail-flagged/blocked (e.g. a prompt-injection case).
   */
  expectFlagged?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eval-runs".
 */
export interface EvalRun {
  id: number;
  name: string;
  agent: number | Agent;
  status: 'queued' | 'running' | 'succeeded' | 'failed';
  caseCount?: number | null;
  passed?: number | null;
  failed?: number | null;
  /**
   * Mean case score 0..1 across the cases.
   */
  score?: number | null;
  /**
   * Minimum aggregate score (0..1) required to pass the gate.
   */
  passThreshold?: number | null;
  /**
   * Computed by the runner: score >= passThreshold.
   */
  gatePassed?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eval-results".
 */
export interface EvalResult {
  id: number;
  evalRun: number | EvalRun;
  case: number | EvalCase;
  agent?: (number | null) | Agent;
  /**
   * The AgentRun trace produced for this case.
   */
  agentRun?: (number | null) | AgentRun;
  output?: string | null;
  /**
   * JSON array of tool calls the model made.
   */
  toolCalls?: string | null;
  flagged?: boolean | null;
  flagReasons?: string | null;
  pass?: boolean | null;
  score?: number | null;
  /**
   * Why the case passed or failed.
   */
  reasons?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  blogPosts?: {
    /**
     * Allow clients to find blog-posts.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  knowledge?: {
    /**
     * Allow clients to find knowledge.
     */
    find?: boolean | null;
  };
  chatSessions?: {
    /**
     * Allow clients to find chat-sessions.
     */
    find?: boolean | null;
  };
  chatMessages?: {
    /**
     * Allow clients to find chat-messages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create chat-messages.
     */
    create?: boolean | null;
  };
  roles?: {
    /**
     * Allow clients to find roles.
     */
    find?: boolean | null;
  };
  providers?: {
    /**
     * Allow clients to find providers.
     */
    find?: boolean | null;
  };
  agents?: {
    /**
     * Allow clients to find agents.
     */
    find?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Search the site knowledge base for relevant information. Use this to answer questions about the site or its content.
     */
    searchKnowledge?: boolean | null;
    /**
     * List published blog posts with their title, slug and excerpt.
     */
    listContent?: boolean | null;
    /**
     * Get a published blog post by its slug.
     */
    getContent?: boolean | null;
    /**
     * Count published blog posts (reporting example).
     */
    countContent?: boolean | null;
    /**
     * Save a short, non-sensitive fact or preference to long-term memory for use in future conversations. Do not store secrets, credentials, or personal data.
     */
    saveMemory?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'runAgent' | 'reindexKnowledge' | 'indexMemory' | 'summarizeMemory' | 'runEval';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'runAgent' | 'reindexKnowledge' | 'indexMemory' | 'summarizeMemory' | 'runEval') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'knowledge';
        value: number | Knowledge;
      } | null)
    | ({
        relationTo: 'knowledge-chunks';
        value: number | KnowledgeChunk;
      } | null)
    | ({
        relationTo: 'chat-sessions';
        value: number | ChatSession;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: number | ChatMessage;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'agent-runs';
        value: number | AgentRun;
      } | null)
    | ({
        relationTo: 'agent-memories';
        value: number | AgentMemory;
      } | null)
    | ({
        relationTo: 'guardrails';
        value: number | Guardrail;
      } | null)
    | ({
        relationTo: 'eval-cases';
        value: number | EvalCase;
      } | null)
    | ({
        relationTo: 'eval-runs';
        value: number | EvalRun;
      } | null)
    | ({
        relationTo: 'eval-results';
        value: number | EvalResult;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  author?: T;
  published?: T;
  publishedDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge_select".
 */
export interface KnowledgeSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  file?: T;
  sourceUrl?: T;
  visibility?: T;
  owner?: T;
  allowedRoles?: T;
  extractedText?: T;
  indexStatus?: T;
  chunkCount?: T;
  indexError?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-chunks_select".
 */
export interface KnowledgeChunksSelect<T extends boolean = true> {
  knowledge?: T;
  chunkIndex?: T;
  content?: T;
  embeddingModel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions_select".
 */
export interface ChatSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  agent?: T;
  summarizedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  session?: T;
  role?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  models?:
    | T
    | {
        modelId?: T;
        id?: T;
      };
  keyRef?: T;
  apiKey?: T;
  baseUrl?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  status?: T;
  capabilities?: T;
  tools?: T;
  runAccess?: T;
  safetyMode?: T;
  semanticSafety?: T;
  gateEnforced?: T;
  user?: T;
  provider?: T;
  model?: T;
  prompt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs_select".
 */
export interface AgentRunsSelect<T extends boolean = true> {
  agent?: T;
  status?: T;
  triggeredBy?: T;
  input?: T;
  output?: T;
  error?: T;
  flagged?: T;
  flagReasons?: T;
  session?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-memories_select".
 */
export interface AgentMemoriesSelect<T extends boolean = true> {
  agent?: T;
  owner?: T;
  kind?: T;
  content?: T;
  session?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guardrails_select".
 */
export interface GuardrailsSelect<T extends boolean = true> {
  name?: T;
  enabled?: T;
  direction?: T;
  action?: T;
  pattern?: T;
  flags?: T;
  replacement?: T;
  agent?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eval-cases_select".
 */
export interface EvalCasesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  agent?: T;
  enabled?: T;
  type?: T;
  match?: T;
  input?: T;
  expected?: T;
  expectFlagged?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eval-runs_select".
 */
export interface EvalRunsSelect<T extends boolean = true> {
  name?: T;
  agent?: T;
  status?: T;
  caseCount?: T;
  passed?: T;
  failed?: T;
  score?: T;
  passThreshold?: T;
  gatePassed?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eval-results_select".
 */
export interface EvalResultsSelect<T extends boolean = true> {
  evalRun?: T;
  case?: T;
  agent?: T;
  agentRun?: T;
  output?: T;
  toolCalls?: T;
  flagged?: T;
  flagReasons?: T;
  pass?: T;
  score?: T;
  reasons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  blogPosts?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  knowledge?:
    | T
    | {
        find?: T;
      };
  chatSessions?:
    | T
    | {
        find?: T;
      };
  chatMessages?:
    | T
    | {
        find?: T;
        create?: T;
      };
  roles?:
    | T
    | {
        find?: T;
      };
  providers?:
    | T
    | {
        find?: T;
      };
  agents?:
    | T
    | {
        find?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        searchKnowledge?: T;
        listContent?: T;
        getContent?: T;
        countContent?: T;
        saveMemory?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRunAgent".
 */
export interface TaskRunAgent {
  input: {
    agentId: number;
    input: string;
    sessionId?: string | null;
    runId?: number | null;
  };
  output: {
    runId?: number | null;
    sessionId?: string | null;
    output?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskReindexKnowledge".
 */
export interface TaskReindexKnowledge {
  input: {
    knowledgeId: number;
  };
  output: {
    chunkCount?: number | null;
    status?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIndexMemory".
 */
export interface TaskIndexMemory {
  input: {
    memoryId: number;
  };
  output: {
    status?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSummarizeMemory".
 */
export interface TaskSummarizeMemory {
  input: {
    agentId: number;
    sessionId: string;
  };
  output: {
    memoryId?: number | null;
    status?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRunEval".
 */
export interface TaskRunEval {
  input: {
    evalRunId: number;
  };
  output: {
    status?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}